#!/bin/sh

BRANCHES=$(git branch -a | sed 's/^..//')

if [ -z "$BRANCHES" ]; then
  echo "No branches found."
  exit 0
fi

DEFAULT_BRANCH=""

if echo "$BRANCHES" | grep -q "^remotes/origin/main$"; then
  DEFAULT_BRANCH="origin/main"
elif echo "$BRANCHES" | grep -q "^remotes/origin/master$"; then
  DEFAULT_BRANCH="origin/master"
elif echo "$BRANCHES" | grep -q "^main$"; then
    DEFAULT_BRANCH="main"
elif echo "$BRANCHES" | grep -q "^master$"; then
    DEFAULT_BRANCH="master"
else
  echo "No default branch found."
  exit 1
fi

git branch --merged | grep -v "\*" | xargs git branch -dµ